# Generated by Django 3.1.2 on 2020-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='correct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='errors',
            field=models.IntegerField(null=True),
        ),
    ]
