# Generated by Django 3.1.2 on 2020-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0002_auto_20201127_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='fname',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
