# Generated by Django 3.1.2 on 2020-11-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0003_auto_20201127_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='studid',
            field=models.IntegerField(),
        ),
    ]
