# Generated by Django 3.1.2 on 2020-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0004_auto_20201106_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='100: 4x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='101: 9x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='102: 7x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='103: 7x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='104: 4x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='105: 8x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='106: 9x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='107: 8x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='108: 7x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='109: 6x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='10: 6x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='110: 9x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='111: 6x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='112: 8x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='113: 3x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='114: 6x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='115: 6x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='116: 2x0',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='117: 8x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='118: 6x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='119: 7x2',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='11: 3x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='120: 10x1',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='12: 9x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='13: 4x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='14: 6x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='15: 7x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='16: 9x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='17: 4x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='18: 6x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='19: 3x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='1: 6x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='20: 8x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='21: 9x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='22: 4x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='23: 5x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='24: 8x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='25: 6x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='26: 7x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='27: 4x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='28: 3x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='29: 7x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='2: 8x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='30: 10x10',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='31: 7x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='32: 8x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='33: 1x5',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='34: 8x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='35: 6x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='36: 0x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='37: 5x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='38: 9x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='39: 8x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='3: 6x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='40: 7x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='41: 3x2',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='42: 4x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='43: 6x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='44: 8x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='45: 7x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='46: 3x2',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='47: 4x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='48: 9x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='49: 3x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='4: 2x2',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='50: 4x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='51: 6x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='52: 3x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='53: 5x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='54: 4x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='55: 9x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='56: 3x0',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='57: 7x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='58: 8x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='59: 3x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='5: 5x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='60: 5x5',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='61: 6x0',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='62: 7x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='63: 1x1',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='64: 4x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='65: 8x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='66: 7x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='67: 9x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='68: 8x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='69: 6x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='6: 7x5',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='70: 6x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='71: 8x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='72: 9x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='73: 7x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='74: 3x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='75: 7x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='76: 6x5',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='77: 9x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='78: 6x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='79: 8x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='7: 3x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='80: 6x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='81: 2x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='82: 9x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='83: 7x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='84: 4x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='85: 3x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='86: 7x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='87: 6x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='88: 9x7',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='89: 1x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='8: 9x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='90: 9x2',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='91: 7x4',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='92: 9x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='93: 7x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='94: 9x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='95: 7x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='96: 8x3',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='97: 6x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='98: 4x9',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='99: 8x8',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='multi',
            name='9: 8x6',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
    ]
