# Generated by Django 3.1.2 on 2020-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0005_auto_20201127_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
