# Generated by Django 3.1.2 on 2020-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0009_auto_20201108_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.AddField(
            model_name='student',
            name='week',
            field=models.CharField(default='12', max_length=200),
            preserve_default=False,
        ),
    ]
