# Generated by Django 3.1.2 on 2020-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0010_auto_20201114_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
