# Generated by Django 3.1.2 on 2020-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0011_auto_20201127_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
