# Generated by Django 3.1.2 on 2020-11-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0011_auto_20201115_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='abc123', max_length=50),
            preserve_default=False,
        ),
    ]
