# Generated by Django 3.1.2 on 2020-11-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0012_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
