# Generated by Django 3.1.2 on 2020-11-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0013_auto_20201116_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
