# Generated by Django 3.1.2 on 2020-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0014_auto_20201127_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='tid',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
