# Generated by Django 3.1.2 on 2020-11-26 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0015_auto_20201117_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('fname', models.CharField(max_length=80)),
                ('klass', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['week']},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='M1',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='M2',
            new_name='errors',
        ),
        migrations.RemoveField(
            model_name='test',
            name='M3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='M4',
        ),
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='tid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='week',
            field=models.PositiveSmallIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='test',
            name='studid',
            field=models.ForeignKey(default=11111, on_delete=django.db.models.deletion.SET_DEFAULT, to='mu.stud', verbose_name='id'),
        ),
    ]
