# Generated by Django 3.1.2 on 2020-11-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0015_auto_20201127_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='studid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mu.stud'),
        ),
    ]
