# Generated by Django 3.1.2 on 2020-11-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0016_auto_20201126_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='multi',
            name='correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multi',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='multi',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='multi',
            name='errors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multi',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='multi',
            name='studid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='mu.stud', verbose_name='id'),
        ),
        migrations.AddField(
            model_name='multi',
            name='tid',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='multi',
            name='week',
            field=models.PositiveSmallIntegerField(default=47),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='studid',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='mu.stud'),
        ),
    ]
