# Generated by Django 3.1.2 on 2020-11-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0016_auto_20201127_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='stuid',
            new_name='studid',
        ),
    ]
