# Generated by Django 3.1.2 on 2020-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0017_auto_20201126_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='week',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
