# Generated by Django 3.1.2 on 2020-12-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0018_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'ordering': ['klasser']},
        ),
    ]
