# Generated by Django 3.1.2 on 2020-11-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0018_auto_20201126_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
