# Generated by Django 3.1.2 on 2020-11-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0019_auto_20201126_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multi',
            name='week',
        ),
    ]
