# Generated by Django 3.1.2 on 2020-12-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0020_auto_20201201_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='week',
            field=models.PositiveSmallIntegerField(default=45, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='klasser',
            field=models.CharField(choices=[('1a', '1a'), ('2a', '2a'), ('3a', '3a'), ('4a', '4a'), ('5a', '5a'), ('9b', '9b')], default=('1a', '1a'), max_length=2),
        ),
    ]
