# Generated by Django 3.1.2 on 2020-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0020_remove_multi_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='multi',
            name='week',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
