# Generated by Django 3.1.2 on 2020-11-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0021_multi_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multi',
            name='studid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='mu.stud'),
        ),
    ]
